name: CI

on:
  push:
    branches:
      - "master"
      - "ci"
      - "v[0-9]+.[0-9x]+x"
  pull_request:
    branches:
      - "master"
      - "v[0-9]+.[0-9x]+x"

jobs:
  create-virtualenv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        python-version: [ '3.5', '3.6', '3.7', '3.8', '3.9' ]
        python-version: [ '3.5' ]
    steps:
      - name: source code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: virtualenv cache
        uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - name: pip cache
        uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Install Python dependencies
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        env:
          POETRY_VERSION: 1.1.4
        run: |
          pip install 'pip==20.3.1'
          pip install 'setuptools==51.0.0'
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          source $HOME/.poetry/env
          poetry install --no-interaction

      - name: Log currently installed packages and versions
        run: pip list

#  linter:
#    needs: create-virtualenv
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-python@v2
#      - uses: syphar/restore-virtualenv@v1
#        id: cache-virtualenv
#
#      - run: flake8
#      - run: pydocstyle
#      - run: isort . --diff --check-only
#      - run: black --check --diff .
#
#  tests:
#    needs: create-virtualenv
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-python@v2
#      - uses: syphar/restore-virtualenv@v1
#        id: cache-virtualenv
#
#      - run: py.test
